DCOS/javascript 0.1.0
dcos/javascript pull request #1
Opened 2017-03-22 18:57 UTC by nLight

This PR nukes pretty much everything. 
Please review and let's cut it for now as it is such a rabbit hole.

After an offline discussion with @orlandohohmeier we've decided to have this repo dependent on airbnb and override DCOS specific things instead of changing rules in place as we find airbnb's style guide to be mostly reasonable.

This is now also a single package repo rather then a multi-thing repo and we can reference it in a package.json without having to publish npm packages.

I extracted some overrides from dcos-ui that we think should be global (still wip)

It introduces prettier but with `warn` severity so we can start using `eslint-config-dcos` immediately without enforcing prettier.

To be done: Nuke all the documentation we agree with and keep/change the bits we don't.

2017-03-22 19:58 UTC, mlunoe requested changes
Don't we want to change the main readme to reflect the changes as well?

2017-03-22 19:58 UTC, mlunoe commented on package.json
>    "author": "Harrison Shoff <hi@hshoff.com> (https://twitter.com/hshoff)",
Should we remove `author` here, since this is now completely different?

2017-03-22 20:00 UTC, mlunoe commented
Sorry, missed that last sentence of the description

2017-03-22 22:38 UTC, nLight commented on package.json
>    "author": "Harrison Shoff <hi@hshoff.com> (https://twitter.com/hshoff)",
My idea was to remove the repo completely and start from the scratch. But since we're still forking airbnb we should keep the attribution.

2017-03-22 23:43 UTC, orlandohohmeier commented on package.json
> +  "name": "eslint-config-dcos",
Let's rename it to `dcos-javascript` to reflect the repo name

2017-03-22 23:43 UTC, orlandohohmeier commented on package.json
>    "author": "Harrison Shoff <hi@hshoff.com> (https://twitter.com/hshoff)",
I'm with @mlunoe and think we should eventually remove the author as there is barely any of his work left but would keep him for now.

2017-03-22 23:49 UTC, nLight commented on package.json
> +  "name": "eslint-config-dcos",
Then it won't work with eslint. Eslint requires its plugins to have a specific naming conventions. For config packages it should start with `eslint-config-`

2017-03-23 04:00 UTC, orlandohohmeier commented on package.json
> +  "name": "eslint-config-dcos",
Ah, ok, didn't know that they need to follow a certain naming convention...

2017-03-23 20:29 UTC, orlandohohmeier commented
LGTM 💯 ✨

2017-03-27 23:32 UTC, nLight commented
Should be good to go since we don't remove author at this stage.

2017-03-27 23:34 UTC, mlunoe commented
Ah! It was not clear to me that you are not removing it here. When are we removing it?

2017-03-27 23:47 UTC, nLight commented
@mlunoe I'd do it once we create an orphan repo that doesn't fork airbnb/javascript

2017-03-28 22:44 UTC, orlandohohmeier commented
@mlunoe what do you reckon? Should we nuke this repo and push the changes to a new one or should we land the changes as is?

2017-03-30 16:29 UTC, mlunoe commented
Because this is MIT license and this technically still is a fork of the Airbnb repository, we need to keep the author. Let's merge this and if we deem it necessary we can re-create it.

2017-03-30 16:29 UTC, mlunoe approved these changes

2017-03-30 16:29 UTC, merged